### ISSUE TITLE
Allow port, protocol to be specified (e.g. Pantalaimon support)

### ISSUE THREAD

**Issue by MagicRB** [alphapapa/ement.el#10]
I want to use this with a hosted https://github.com/matrix-org/pantalaimon instance, which will definitely not be running on port 443 but 80, so having the port hardcoded is rather annoying. https://github.com/alphapapa/ement.el/blob/master/ement.el#L163

I'd fix it myself, but my elisp knowledge is not yet at your level :), thanks for this awesome client! looks better than element already.

**Comment by MagicRB** [comment]
with these changes im able to login through pantalaimon but I still am not able to decrypt messages, will need further digging sadly

```diff
@@ -67,14 +67,14 @@
                (path (format "/_matrix/%s/r0/%s" endpoint-category endpoint))
 	       (query (url-build-query-string params))
 	       (filename (concat path "?" query))
-               (url (url-recreate-url
-		     (url-parse-make-urlobj type nil nil host port filename nil data t)))
+               (url (concat "localhost:8080" filename))
                (headers (ement-alist "Content-Type" content-type
                                      "Authorization" (concat "Bearer " token))))
     ;; Omit `then' from debugging because if it's a partially applied
     ;; function on the session object, which may be very large, it
     ;; will take a very long time to print into the warnings buffer.
     ;;  (ement-debug (current-time) method url headers)
+    (message "%s : %s : %s : %s" host port data uri-prefix)
     (plz method url :headers headers :body data :body-type data-type
       :as json-read-fn :then then :else else
       ;; FIXME: Timeout is not necessarily the same as connect-timeout, or shouldn't be.
modified   ement.el
@@ -271,7 +271,7 @@ If no URI is found, prompt the user for the hostname."
                        ;; Parsing error: FAIL_PROMPT.
                        (fail-prompt))))
     (let ((response (condition-case err
-                        (plz-get-sync (concat "https://" hostname "/.well-known/matrix/client")
+                        (plz-get-sync (concat "http://" hostname "/.well-known/matrix/client")
                           :as 'response)
                       (plz-http-error (plz-error-response (cdr err))))))
       (pcase (plz-response-status response)
```

**Comment by alphapapa** [comment]
Hi, thanks for the kind words, I'm glad you like it.

Some work to this regard has been done already.  Please see the branch https://github.com/alphapapa/ement.el/tree/wip/port-tls.  If you can help me test it, that would be great; I don't use Pantalaimon myself.

**Comment by alphapapa** [comment]
Forgot to mention that I need to rebase that branch.  I'll do that soon.

**Comment by MagicRB** [comment]
ill test afterwards, but for today im leaving, cya

**Comment by MagicRB** [comment]
also as for pantalaimon, i think its due to ement not doing anything with verify requests, because new messages show up fine, though i cant send messages either. It's bizarre through and through :man_shrugging:

**Comment by alphapapa** [comment]
My understanding is that Pantalaimon is supposed to be a transparent proxy, so clients aren't supposed to need to know about verification, etc.  But I haven't used it myself, so maybe I'm wrong.  I'll be glad to help support it if I can, but I'll need help from users like you.  :)

**Comment by alphapapa** [comment]
Please let me know if that works for you.  (Specifying the server's URI prefix doesn't work interactively at the moment, so you'll have to eval `(ement-connect ...)`.  If needed, we can figure out a way to do it interactively, as well.)
