### ISSUE TITLE
error in process sentinel:  No clause matching ‘"interrupt "’

### ISSUE THREAD

**Issue by hjozwiak** [alphapapa/ement.el#103]
This came this morning after a package update.
Here is a trace for you.

Debugger entered--Lisp error: (error "No clause matching ‘\"interrupt\n\"’")
  signal(error ("No clause matching ‘\"interrupt\n\"’"))
  error("No clause matching `%S'" "interrupt\n")
  plz--sentinel(#<process plz-request-curl<1>> "interrupt\n")

**Comment by alphapapa** [comment]
Thanks.  This should be fixed by https://github.com/alphapapa/plz.el/commit/4480f4ea248cd433c1f97b2f4364fa84cbd99b08, which will be in plz 0.2.1, which should be available on ELPA within 12 hours.
