### ISSUE TITLE
`ement-room-send-message' should inherit the room's input method.

### ISSUE THREAD

**Issue by vizs** [alphapapa/ement.el#11]
In the read-string call, it would make it much easier to use input methods if inherit-input-method argument was t.  Currently you have to switch to the relevant input method every time (when the minibuffer is in focus) you send a message.

**Comment by alphapapa** [comment]
That will need to be added whenever a new `read-string` call is added, but that should do it for now.  Thanks.

**Comment by vizs** [comment]
Thanks!
