### ISSUE TITLE
Trouble running after install: (file-missing Cannot open load file No such file or directory ement)

### ISSUE THREAD

**Issue by presto8** [alphapapa/ement.el#110]
I am using Doom. I added this to the packages.el:
`    (package! ement)                                                                                                                                     `

I also tried this:
```
    (package! ement                                                                                                                                          
      :recipe (:host github :repo "alphapapa/ement.el"))          
```

Both have the same result:

(file-missing Cannot open load file No such file or directory ement)

On startup. Just wondering if there are some install steps I am missing perhaps? Thanks!

**Comment by alphapapa** [comment]
I can't offer support for DOOM.  If you follow the instructions in the readme, the package will work.

**Comment by presto8** [comment]
Ok, thanks! Let me try it with a clean Emacs (no Doom). I didn't think it was a Doom issue but maybe it is.

**Comment by presto8** [comment]
It works perfectly with vanilla emacs and installing from ELPA. I should have tried that first, I apologize! I am new to Doom and thought the package! command would be pretty much equivalent to package-install but apparently now...

**Comment by alphapapa** [comment]
I'm glad to hear that it's working for you.

I admire DOOM as a project, but if I had a nickle for every DOOM user who's reported problems that are caused by its idiosyncrasies...

Anyway, if you'd like to join the `#ement.el:matrix.org` chat room, there are several DOOM users who can help you improve the way it works with Ement.

**Comment by trevarj** [comment]
The solution to this is to just restart emacs. `doom sync` won't be enough.
