### ISSUE TITLE
user-id homeserver case sensitivity

### ISSUE THREAD

**Issue by progfolio** [alphapapa/ement.el#114]
I can successfully connect via either of the following with the same credentials:

```emacs-lisp
(ement-connect :user-id "@nv-elisp:Matrix.org") ;; capital M
(ement-connect :user-id "@nv-elisp:matrix.org") ;; lowercase m
```

However, connecting with the first will lead to the "You may only edit your own messages" user-error when attempting to edit my messages due to the `equal` comparison of the sender/user ement-user-id in `ement-room-edit-message`.

I'm not all that familiar with the Matrix spec, so the solution may very well be "make sure the homeserver case matches when you connect", but I found it unusual that I was able to connect at all if that portion of the id is case sensitive.

I'm now wondering if this is also the root cause of #84 (which seems to have gone away after connecting with the second :user-id from above, but did not come back if I reconnected with the first...odd).

**Comment by alphapapa** [comment]
Following the trail from #84 again, the relevant code in Synapse appears to be here:

https://github.com/matrix-org/synapse/blob/6d47b7e32589e816eb766446cc1ff19ea73fc7c1/synapse/server.py#L341

So it appears that the two strings are compared with `==`, which AFAIK is case-sensitive.  Also, the method defined after that one appears to work similarly, but I don't know where it's used in Synapse: https://github.com/matrix-org/synapse/blob/6d47b7e32589e816eb766446cc1ff19ea73fc7c1/synapse/server.py#L344

However, the behavior you report would suggest that other code paths in Synapse compare the hostnames case-insensitively, which is probably why it allows you to authenticate for other purposes.

As well, the Matrix spec explains: https://spec.matrix.org/v1.5/appendices/#identifier-grammar

> Server names must be treated case-sensitively: in other words, @user:matrix.org is a different person from @user:MATRIX.ORG.

So it appears that you should avoid using uppercase letters in your MXIDs.
