### ISSUE TITLE
Allow to explicitly state server's hostname when calling ement-connect.

### ISSUE THREAD

**Issue by vizs** [alphapapa/ement.el#12]
Right now, if the server's well-known URI is not known, ement asks the user to input the server hostname.  Having an optional arg to explicitly specify the server hostname will be convenient as I usually call `ement-connect' as follows:

    (ement-connect "<myaccount>" (pass "<myaccount>"))
    
where the `pass' function prompts me for the master password.  If the optional arg was added, it would be:

    (ement-connect "<myaccount>" (pass "<myaccount>") "serverhostname")

saving me from having to type the server hostname _every time_.

**Comment by alphapapa** [comment]
Please let me know if that works for you.  (Specifying the server's URI prefix doesn't work interactively at the moment, so you'll have to eval `(ement-connect ...)`.  If needed, we can figure out a way to do it interactively, as well.)

**Comment by vizs** [comment]
This works, thanks!
