### ISSUE TITLE
Likely misconfigured homeserver

### ISSUE THREAD

**Issue by Mrsjh** [alphapapa/ement.el#120]
error in process sentinel: plz: Curl error
error in process sentinel: Curl error
Ement: Checking server’s login flows...
error in process sentinel: ement-api-error: Ement API error: "28: Operation timeout."
error in process sentinel: Ement API error: "28: Operation timeout."

ement version:0.5.2

These occured when I logged in.
Can anyone help me?

I just interactively called the function `ement-connect` , input my username like `@xxx:matrix.org`,and input password
then it said `Auto-discovery of server's well-known URI failed Input server hostname , or leave blank to use server name`
and I input `https://matrix-client.matrix.org` 
That's all.

**Comment by alphapapa** [comment]
Hello,

1. Are you actually using the matrix.org homeserver, or a different one?
2. Please read the message carefully: it says to input the hostname or leave blank, but you have input a URL.
3. The fact that auto-discovery of the URI failed usually indicates a misconfigured homeserver.  That probably means that you aren't using the matrix.org homeserver, and that the one you are using isn't configured properly.

**Comment by Mrsjh** [comment]
` Warning (emacs): Ement: ‘plz’ request for .well-known URI signaled an error: (plz-curl-error . #s(plz-error (28 . "Operation timeout.") nil nil))`

I uncommented the form in the ement.el and got this.

And then I found the function `ement--hostname-uri` which called `plz` to get the response from `https://matrix.org/.well-known/matrix/client`

And then I called `plz` in the `*scratch*` buffer to request the URL "https://matrix.org/.well-known/matrix/client" manually.
Finally it signaled the same error in the `"Backtrace"` buffer.

Maybe it is the plz's fault I think, I don't know about the plz package at all. But I had configured the **url-proxy-services** and it worked well both in eww and xwidget-browser.

**Comment by alphapapa** [comment]
You're using a proxy, or a VPN, or both?

Anyway, if your connectivity is blocked without using a proxy, you would appear to be experiencing the issue discussed in #77.  If you add the appropriate curl arguments to use a proxy, it will likely work.

Since this appears to be #77, I'm closing this issue.  Please continue the discussion there.
