### ISSUE TITLE
[FR] Separate history for username prompt in `ement-connect'

### ISSUE THREAD

**Issue by yantar92** [alphapapa/ement.el#122]
Currently, global minibuffer history is being used, which is mostly useless - one don't usually have ement username there.
I think it would be more useful to provide a separate input history instead.
WDYT?

**Comment by alphapapa** [comment]
Hi Ihor,

Generally, I've no objection to this.  However, I expect that most users won't have many different MXIDs to enter, and after enabling `ement-save-sessions`, it's not necessary to type one's MXID again, so I don't know if it's necessary.  Are you saving your session, or are you making a new one each time you connect?

**Comment by yantar92** [comment]
Adam Porter ***@***.***> writes:

> Are you saving your session, or are you making a new one each time you connect?

I still need to figure out if it is actually saved or not. So far, it
looks like I have to connect after every restart because of pantalaimon
(and thus having to pass :uri-prefix).
But I still need to investigate.

> Generally, I've no objection to this.  However, I expect that most
> users won't have many different MXIDs to enter, and after enabling
> `ement-save-sessions`, it's not necessary to type one's MXID again, so
> I don't know if it's necessary.

Probably. But this FR is raises a question whether other prompts should
provide separate history. Like in `ement-send-direct-message',
`ement-set-display-name', `ement-room-set-display-name',
`ement-room-send-file', `ement-room-send-image', etc.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by alphapapa** [comment]
Would having separate history variables for those prompts be useful?  Unless the user is persisting them to disk, they wouldn't last, anyway.  And how long would such history be useful?

Again, I'm not necessarily opposed to it, but I'm not sure it would be worth doing.

**Comment by yantar92** [comment]
Adam Porter ***@***.***> writes:

> Would having separate history variables for those prompts be useful?
> Unless the user is persisting them to disk, they wouldn't last,
> anyway.  And how long would such history be useful?

Uploaded file name history can be useful when one wants to upload the
file to multiple rooms within one session - the need that is not
uncommon I guess. Sending file may incorporate image history as well.

Setting display name may also be something people do repeatedly in
multiple rooms.

Sending direct message also tends to happen to same people.

So, I do see dedicated history being useful. At least, I am often
annoyed by unrelated prompt history popping up in the completion where
it is not supposed to, logically.

P.S. I will have to switch back to web ui again. Pantalaimon is giving
too much headaches with encrypted messages not being synced without
restarting.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by alphapapa** [comment]
https://github.com/alphapapa/ement.el/commit/fbf40d66edc2a8f09a2793d9cbc89cf07e792c86 also includes lists for messages, filenames, etc.

@yantar92 Thanks.
