### ISSUE TITLE
Error when connecting on account that hasn't joined rooms yet

### ISSUE THREAD

**Issue by Kabouik** [alphapapa/ement.el#123]
I was very happy to find an emacs package for Matrix so I immediately installed it from `list-packages`, but I am getting the following issue when running `ement-connect`:

```
Ement: Response arrived after 30.21 seconds.  Reading 795 JSON response...
Ement: Reading JSON took 0.00 seconds
Ement: Reading events... 
Ement: Sync request sent, waiting for response...
error in process sentinel: taxy-magit-section-format-header: Invalid format operation %n
error in process sentinel: Invalid format operation %n
```

This is on Guix system, and I get the same error after trying to uninstall `emacs-magit`. I have tried both `emacs-magit@3.3.0-2.c883fab` and `emacs-magit@20230125.1440`, same symptoms.

The only way I can install `ement-el` is from `list-packages` because the version on Guix seems to have dependency conflicts. However, when I install it, I get the above error, but also other ones when I restart emacs

```
Unable to activate package ‘transient’.
Required package ‘compat-28.1.1.0’ is unavailable
Unable to activate package ‘taxy-magit-section’.
Required package ‘magit-section-3.2.1’ is unavailable
Unable to activate package ‘taxy-magit-section’.
Required package ‘magit-section-3.2.1’ is unavailable
Unable to activate package ‘ement’.
Required package ‘taxy-magit-section-0.12.1’ is unavailable
```

**Comment by alphapapa** [comment]
Hello,

Although I'm glad to have Ement in Guix, I can't offer support for that packaging, because I have no control over it.  I recommend installing the required packages directly from GNU ELPA into a clean Emacs configuration, e.g. using https://github.com/alphapapa/with-emacs.sh.  If you do that, it should work.

**Comment by oantolin** [comment]
Oh, here's a clue: I had initially tried to use `ement.el` right after creating an account, before joining any rooms. That's when I got the `%n` error. So next I joined a room using a different client and then tried to log in with `ement.el` again and this time it worked. So maybe it's a bug triggered by an empty room list?

**Comment by alphapapa** [comment]
> Oh, here's a clue: I had initially tried to use `ement.el` right after creating an account, before joining any rooms. That's when I got the `%n` error. So next I joined a room using a different client and then tried to log in with `ement.el` again and this time it worked. So maybe it's a bug triggered by an empty room list?

Yes, that's likely the case.  I haven't tested logging in on an account that hasn't yet joined any rooms.

**Comment by Kabouik** [comment]
I think you're right @oantolin: my use case was also with an account not in any room yet, and I believe this very error message vanished when I joined a room using the Element web UI first. I didn't notice that initially because I was still experiencing some other issues which I thought were all related, and I wanted to give troubleshooting a little more time before reporting here, to determine whether those issues would be related to my system or to ement.el.
