### ISSUE TITLE
Can’t connect (self-hosted homeserver)

### ISSUE THREAD

**Issue by philippludwig** [alphapapa/ement.el#125]
So I am using the command `ement-connect`, enter my user `@philipp:<myserver>` (I am running a Matrix instance on my own domain) and get this:

```
error in process sentinel: plz--sentinel: HTTP error
error in process sentinel: HTTP error
Ement: Checking server’s login flows...
error in process sentinel: ement-api-error: Ement API error: "3: URL malformed. The syntax was not correct."
error in process sentinel: Ement API error: "3: URL malformed. The syntax was not correct."
```

Other clients like Quaternion work fine with this account / server. What could I try now?

**Comment by viiru-** [comment]
Which server are you using? Could https://github.com/alphapapa/ement.el/issues/66 be relevant?

**Comment by philippludwig** [comment]
As stated, I am running my own Server. I am not exactly sure what the changes in #66 are; what is the correct format for the server URL?

**Comment by alphapapa** [comment]
@philippludwig Which server software are you running?  i.e. Synapse, Dendrite, Conduit...?

**Comment by philippludwig** [comment]
I am running Synapse. I also enabled the `well-known` setting and verified that it is indeed served correctly. The problem persists, though.

**Comment by alphapapa** [comment]
@philippludwig If you would, please load the latest development version of `plz` into your Emacs instance and try again to connect.  You can find the code here: https://raw.githubusercontent.com/alphapapa/plz.el/master/plz.el  If it still doesn't work, please provide more information such as Emacs version and where/how it was built, what platform you're running on, Curl version, etc.  Thanks.

**Comment by alphapapa** [comment]
@philippludwig Thanks.  Please evaluate this form, replacing `hostname` with the hostname of your server in a string, and show me the result:
```el
(plz 'get (concat "https://" hostname "/.well-known/matrix/client")
                          :as 'response :then 'sync)
```
Then please run this command in a shell and show me the result:
```
curl -v https://YOURSERVERHOSTNAME/.well-known/matrix/client
```
You may redact the hostname, IP address, and any other sensitive information from the output if you like.

**Comment by philippludwig** [comment]
I guess I have to apologize; when doing these steps, I realized I mis-read your instructions and configured `well-known` only for the server part, not the client:

```
$ curl https://<myserver>/.well-known/matrix/server
{"m.server":"<myserver>:443"}
$ curl https://<myserver>/.well-known/matrix/client
.well-known not available
```

I was not realizing that. So the root of the issue was that I did not set `public_baseurl` in my `homeserver.yaml` – this is documented here: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#public_baseurl (noting for future visitors).

Now everything works fine. I am sorry for wasting your time with this issue; now I am just wondering why the other Matrix clients did not complain.

**Comment by alphapapa** [comment]
@philippludwig Thanks for following up on that and explaining the solution.

I also wonder why other clients didn't complain.  Probably they executed a fallback, which AFAIK Ement should also do, but maybe I made a mistake in implementing it.
