### ISSUE TITLE
Replies and edited messages can't be edited

### ISSUE THREAD

**Issue by oantolin** [alphapapa/ement.el#126]
When I try using `ement-room-edit-message` to edit a reply I've written, I get a user error that says: "Only original messages may be edited, not the edit events themselves". Editing a non-reply message I wrote works fine.

**Comment by alphapapa** [comment]
Yes, this needs to be fixed.  See: https://github.com/alphapapa/ement.el/blob/28de42d653cc1e254cc3dccfcb685db947cdde4c/ement-room.el#L1635-L1638
