### ISSUE TITLE
`ement-view-space` doesn't work when in any ement related buffer

### ISSUE THREAD

**Issue by MagicRB** [alphapapa/ement.el#127]
When `ement-view-space` is executed in any ement related buffer, it tries to pull the current buffer's room, or the room at point in the case of the list buffer, as the space to view. Which obviously fails. This behavior should be overwritten (I think it should be default, or another interactive command should be provided) by calling `ement-view-space` with a single prefix argument. Which works but only outside of ement buffers, in those it still takes the space room from somewhere and hopes for the best.

**Comment by alphapapa** [comment]
Hm, it's supposed to filter out non-space rooms from the completion candidates.  I'll look into this when I get a chance.  Thanks.
