### ISSUE TITLE
Symbol’s value as variable is void: sender

### ISSUE THREAD

**Issue by dyereh** [alphapapa/ement.el#13]
I am able to sucessfully run `ement-connect` and can send messages in rooms. However, I cannot see any of the messages in any of the room buffers and it seems that many commands results in `Symbol’s value as variable is void: sender`

Ement: Checking server’s login flows...
Ement: Logging in with password...
Ement: Sync request sent, waiting for response...
Ement: Response arrived after 1.79 seconds.  Reading 1.1M JSON response...
Ement: Reading JSON took 0.15 seconds
Ement: Reading events... 
Ement: Sync request sent, waiting for response...
Ement: Sync done.  Use commands ‘ement-list-rooms’ or ‘ement-view-room’ to view a room.
ement-room--format-message: Symbol’s value as variable is void: sender
ement-room--format-message: Symbol’s value as variable is void: sender

I'm running Doom on Emacs 28.0.50

I don't have any custom configuration for ement - any suggestions?

**Comment by alphapapa** [comment]
How did you install it?

**Comment by dyereh** [comment]
I believe it's a doom macro that ultimately uses straight.el

```
(package! plz
  :recipe (:host github :repo "alphapapa/plz.el"))

(package! ement
  :recipe (:host github :repo "alphapapa/ement.el"))
```

**Comment by alphapapa** [comment]
It would appear to be a macro expansion problem (the `pcase-let*` macro must not be getting expanded properly).  I can't explain why.  It works for me, and it works for other Doom users who chat in `#ement.el:matrix.org`.  Please try to reproduce in `emacs -q` or with https://github.com/alphapapa/emacs-sandbox.sh

**Comment by dyereh** [comment]
Sounds good - I used your emacs-sandbox.sh with the following config file

```elisp
;; Install and load `quelpa-use-package'.
(package-install 'quelpa-use-package)
(require 'quelpa-use-package)

;; Install `plz' HTTP library (not on MELPA yet).
(use-package plz
  :quelpa (plz :fetcher github :repo "alphapapa/plz.el"))

;; Install Ement.
(use-package ement
  :quelpa (ement :fetcher github :repo "alphapapa/ement.el"))
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(ement ts s dash plz quelpa-use-package)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

Seems to be about the same behavior except that the list of rooms doesn't pop up until I run `M-x ement-list-room`. I can still send messages but can't see them in the buffer (getting errors along the way)

```
Saving file /home/edyer/emacs-sandbox.sh/ement-config/init.el...
Wrote /home/edyer/emacs-sandbox.sh/ement-config/init.el
Loading /home/edyer/emacs-sandbox.sh/ement-config/init.el (source)...done
Making completion list...
Ement: Checking server’s login flows...
Ement: Logging in with password...
Ement: Sync request sent, waiting for response...
Ement: Response arrived after 2.21 seconds.  Reading 1.1M JSON response...
Ement: Reading JSON took 0.36 seconds
Ement: Reading events... 
error in process sentinel: progn: Wrong type argument: stringp, nil
error in process sentinel: Wrong type argument: stringp, nil
memq: Symbol’s value as variable is void: sender
You can run the command ‘ement-room-send-message’ with RET
```
What version of emacs are you developing on? Does the sandbox script get rid of any lingering configuration besides that in the passed folder? I will try from emacs27 later

**Comment by alphapapa** [comment]
I've been testing it on Emacs 26.3 and 28.0.50.  AFAIK it works fine, and several other people are using it daily without problems like this.  Please make sure your Emacs 28 build is current and that you have the latest version of this package installed.

**Comment by alphapapa** [comment]
The fix I just pushed seems to fix it.  I don't know why it would happen on Emacs 28.0.50, because that should include a recent version of the `map` library.  If that doesn't fix it, please make sure you have `map` >= 2.1 installed, and make sure that that version is being loaded before any older version that might be in your `load-path`.  ISTR Doom users having issues with this before; it has its own way of managing packages...

**Comment by ReggieMarr** [comment]
I hadn't noticed this last week but I've been dealing with the same issue as @dyereh since pulling down the latest today. I've tried running the sandbox with the same config. I am running emacsng but I don't think that would be the problem since that hasn't changed since last week and it was rebased off emacs 28 not too long ago.

**Comment by dyereh** [comment]
Yes I also tried on 27.2 and got the same issue (using sandbox.sh) so I don't think its an emacs config/build issue but I don't have the debugging knowledge to know what to do next. It seems that it 'half' works - a subset of rooms will be available when listing rooms. If there is anyway to enable more debugging logs let me know

**Comment by alphapapa** [comment]
You have to install version 2.1 or greater of the `map` package and make sure it's loaded before any older versions that might also be present.  AFAICT, if your installation process doesn't account for the required dependency versions in the headers, that's a flaw in whatever installation process you're using.

**Comment by dyereh** [comment]
Alright so it seems that emacs 27.2 (at least my build has map 2.0 built in) I tried to install 3.0 and they both appear now. Is there a way to know that the install 3.0 would override the built-in 2.0? 
![image](https://user-images.githubusercontent.com/19615394/128943498-cd7a720a-2222-4f53-95b8-3fb971ddd428.png)

**Comment by alphapapa** [comment]
> Is there a way to know that the install 3.0 would override the built-in 2.0?

Well, does it work now?  ;)

Anyway, you can look at the list of directories in `load-path`.  Assuming you have a standard system, `package` should set it up correctly.  You will generally need to restart Emacs after upgrading a package in order for it to take effect, though.

**Comment by ReggieMarr** [comment]
FYI I checked mine and I only have version 3.0
![list-packages_map](https://user-images.githubusercontent.com/13193444/128949483-3cf3d629-779b-44f3-bc77-6a629d1c4458.png)

**Comment by alphapapa** [comment]
@ReggieMarr Then please reinstall Ement according to the instructions in the readme.  I've tested it many times, and it's known to work.  If you still have problems, please try to reproduce in a clean configuration.  These macro expansion issues always turn out to be configuration problems, or caused by using non-standard frameworks, or package management tools that don't handle dependencies properly, etc.

**Comment by alphapapa** [comment]
@ReggieMarr On second look, please look at your screenshot carefully.  It says that map 3.0 is "available", not "installed."

**Comment by dyereh** [comment]
> Well, does it work now? ;)

Haha unfortunately not - will try again from a clean config

**Comment by alphapapa** [comment]
I know it works, because I use it, and a number of other people do, too.  In fact, 2 new users joined the #ement.el:matrix.org room today.  :)
