### ISSUE TITLE
[FR] Send device_id and initial_device_display_name on login

### ISSUE THREAD

**Issue by viiru-** [alphapapa/ement.el#134]
Sending a stable `device_id` would make it possible to do automatic server-side session management (see https://spec.matrix.org/v1.3/client-server-api/#relationship-between-access-tokens-and-devices). I'd recommend a one-way hash of something like `Ement-<username>@<hostname>`.

The `initial_device_display_name` is meant to be human readable and make it easy to manually terminate sessions on devices that no longer exist and so on. It should perhaps be customizable. I'd use something similar as the default (include the string "Ement" and the username and hostname).

(note that I'm actively not submitting PRs that would just get stuck while waiting for the FSF paperwork, if that clears I will probably work on this myself unless someone else beats me to it)

**Comment by alphapapa** [comment]
Thanks for bringing this to my attention.  Definitely want to do this.  :)
