### ISSUE TITLE
Enhancements to composition buffers

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/ement.el#140]
See https://github.com/alphapapa/ement.el/issues/31#issuecomment-1504301452 and https://github.com/alphapapa/ement.el/issues/31#issuecomment-1504306475:

@phil-s

> I believe this will be useful for me:
> 
> ```emacs-lisp
> ;; Open Ement Compose buffers below the Room buffer.
> (add-to-list 'display-buffer-alist
>              (cons "^\\*Ement compose: "
>                    (cons 'display-buffer-below-selected
>                          '((window-height . 6)
> 			   (inhibit-same-window . t)
>                            (reusable-frames . nil)))))
> ```

Yeah, that looks handy.  Might add that to the docs.

> 
> I also notice that these buffers are in `fundamental-mode`. At minimum, I'd suggest:
> 
> ```emacs-lisp
> (define-derived-mode ement-compose-mode text-mode "Ement Compose"
>   "Major mode for composing messages for Matrix rooms.")
> ```

I think I have a TODO around here somewhere for that...

> A key binding to abort the message + delete the window would be useful. 

You can simply kill the buffer, like any other buffer.  But if you really want, we could add something like `C-c C-k`, I guess, similar to Magit commit buffers.

> And if there were an option to send the message directly without going via the minibuffer, I'd probably have pretty much everything I wanted at that point.

I'm open to that idea, sure.  What keybinding would you suggest?  Maybe `C-c C-RET`, or `C-c RET`?

**Comment by alphapapa** [comment]
`C-c C-c` would be fine if it weren't for supporting Org mode in composition buffers, in which `C-c C-c` has an existing meaning.  That's why I went with `C-x C-s` for the binding to return to composing in the minibuffer.

**Comment by phil-s** [comment]
Ah, I see.  Your `C-c RET` suggestion sounds pretty good, then.

**Comment by phil-s** [comment]
My IRC muscle-memory continues to try to start composing messages by simply typing (and I have usually typed the first SPC before I've realised I'm doing it wrong, which then takes me to a different room), so I've just done the following.  I know that various letters are bound to other commands, which makes the resulting behaviour inconsistent, but I *think* this will save me more headaches than it creates (or maybe I'll just be more likely to perform unintended room commands... we'll see how it goes...)

I'm putting the code here just in case this is also what someone else wants.

```el
(with-eval-after-load "ement-room"
  (define-key ement-room-mode-map [remap self-insert-command]
    #'my-ement-room-insert-compose-message))

(defun my-ement-room-insert-compose-message ()
  "Begin composing a message."
  (interactive)
  (apply #'ement-room-compose-message (ement-with-room-and-session
					(list ement-room ement-session)))
  (push last-command-event unread-command-events)
  (local-set-key (kbd "C-c C-c") #'ement-room-compose-send)
  (local-set-key (kbd "C-c C-k") #'my-ement-room-compose-abort))

(defun my-ement-room-compose-abort ()
  "Kill the compose buffer and window."
  (interactive)
  (kill-buffer)
  (delete-window))
```

**Comment by phil-s** [comment]
Does this adaptation of `ement-room-compose-send` look right for the "send message directly from the compose buffer" command?

```el
(defun ement-room-compose-send-direct ()
  "Directly send the current compose buffer's contents.
To be called from an `ement-room-compose' buffer."
  (interactive)
  (cl-assert ement-room-compose-buffer)
  (cl-assert ement-room)
  (cl-assert ement-session)
  ;; Trim whitespace.
  (goto-char (point-min))
  (skip-chars-forward " \t\r\n")
  (delete-region (point-min) (point))
  (goto-char (point-max))
  (skip-chars-backward " \t\r\n")
  (delete-region (point) (point-max))
  ;; Prepare message.
  (let ((body (buffer-string))
        (send-message-filter ement-room-send-message-filter)
        (replying-to-event ement-room-replying-to-event)
        (room ement-room)
        (session ement-session))
    (quit-restore-window nil 'kill)
    (ement-view-room room session)
    (let ((ement-room-send-message-filter send-message-filter))
      (when replying-to-event
        (let ((pos (ewoc-location (ement-room--ewoc-last-matching ement-ewoc
                                    (lambda (data)
                                      (eq data replying-to-event))))))
          (setq body (ement-room-with-highlighted-event-at pos
                       body))))
      ;; Send message.
      (ement-room-send-message room session
                               :body body
                               :replying-to-event replying-to-event))))
```

I opted for the more verbose trimming of whitespace in the buffer just to avoid generating additional strings.

**Comment by phil-s** [comment]
I don't actually understand the workflow of moving back to the minibuffer from the compose buffer.

I understand that composing entire messages in the minibuffer can be desirable; and I understand that being able to "upgrade" from the minibuffer to a compose buffer is desirable in cases where the message is more elaborate; but having ended up in a compose buffer, I don't understand why anyone would ever want to go back to the minibuffer as an intermediate step before sending a message.  That seems clunky to me.

(I may be missing the reason for this on account of my not wanting to use the minibuffer for editing messages at all, though.)

**Comment by alphapapa** [comment]
I guess it could be seen as clunky, yes.  My interpretation is that the minibuffer is *the* way to send a message, so the existing functionality just allows you to move the message back and forth between a full buffer and the minibuffer; or it could be that putting it back in the minibuffer serves as a confirmation step after composing a more "serious" message.  

But I've no objection to adding a command to send it directly from the full buffer.  I'd just like to, if possible, make the code as simple as possible, probably by just moving the message back to the minibuffer and then calling the command to send the message from the minibuffer--the message's moving back into the minibuffer should happen without being visible to the user, because redraw shouldn't happen until after it's sent.

**Comment by phil-s** [comment]
My intention is to create a PR at some point to add an option to use the compose-buffer-centric behaviour I'm working on.  I think some of the other users will like it, so I feel it would be a nice option to include.

It more or less gives the feel of the "shell-like prompt" approach, but as it's actually based on the pre-existing compose buffer support I don't think it will require too much in the way of new code (although at this point I've only dealt with writing new messages).  The most disruptive thing I'm doing so far is messing with `ement-room-mode-map`, but I expect I can come up with something which will be clean enough for the purposes of toggling the option on and off.

**Comment by progfolio** [comment]
related: #200 would allow removing the default compose-send behavior and replacing it to the user's content.

**Comment by phil-s** [comment]
I've updated https://github.com/alphapapa/ement.el/issues/140#issuecomment-1639601194 for ement v0.13.

**Comment by phil-s** [comment]
There is now a PR for this work: https://github.com/alphapapa/ement.el/pull/236

Feel free to test and provide feedback.

**Comment by phil-s** [comment]
#246 has been merged (yay!), so I think we can close this.
