### ISSUE TITLE
Possible to load all earlier events? 

### ISSUE THREAD

**Issue by salehmu** [alphapapa/ement.el#141]
Since searching with `M-s o` only works with loaded messages, is it possible to make ement loads all the events once a room opened? (at least with certain rooms)

**Comment by alphapapa** [comment]
You can load earlier events with `M-v`, or `C-u M-v` to input a number of events.

Loading *all* earlier events would likely be problematic, depending on the size of the room, but theoretically you can.

Searching message content with the API, like Element clients, is planned for the future.

**Comment by alphapapa** [comment]
BTW, please feel free to join the #ement.el:matrix.org chat room, where you could ask questions like this.
