### ISSUE TITLE
Design suggestions!

### ISSUE THREAD

**Issue by Icy-Thought** [alphapapa/ement.el#144]
## Introduction
Firstly, I would like to express my appreciation for all the effort you've put into this wonderful project! :)

Secondly, I had several ideas about how we could potentially "improve" the current UI of ement.el, but unfortunately I lack the necessary emacs-lisp knowledge to implement those features.. :/

## Proposal

1. Add a side-frame where you can find all the spaces / rooms the user has joined. Perhaps something similar to Rougier's [Sideframe](https://github.com/rougier/sideframe) package could be of use.

2. Add margin between the side-frame and the messages to have it stretch in the middle of the page instead of being placed from one end to the other.

## Last words...

If I have better ideas, then I'll make sure to share them!

**Comment by alphapapa** [comment]
Hello,

Thanks for the kind words.  I'm glad it's useful to you.

Have you tried the command `ement-room-list-side-window`?

**Comment by Icy-Thought** [comment]
Yes I did and it managed to solve the issue. Now what remains if for me to figure out how to make it open only with room names displayed rather than the remaining information.

Also, is it possible to have the window be deleted / buffer closed whenever I exit ement?

**Comment by alphapapa** [comment]
See the variable `ement-room-list-columns`.  You can set it to just `'("Name")` and that should do it.

Room buffers should get closed when you run `ement-disconnect`.
