### ISSUE TITLE
`ement-room-list-next-unread` broken

### ISSUE THREAD

**Issue by jeffbowman** [alphapapa/ement.el#149]
Just upgraded ement.el  to version 0.9.1 from ELPA and restarted Emacs.  When I login and there are unread messages in a room, pressing SPC (`ement-room-list-next-unread`) gives this message: `user-error: No buttons!`

This error message appears regardless if there are rooms with unread messages or not. 

No rooms are entered, but I can move to a room and press RET (`ement-room-list-RET`) to enter that room directly.

**Comment by alphapapa** [comment]
Hi Jeff,

Thanks for reporting this.  Please try this commit and let me know if it fixes it: https://github.com/alphapapa/ement.el/commit/cc815b8c01214b912a80af8970bf303f2fc8083e  It seems to work for me.

**Comment by jeffbowman** [comment]
The fix works for me.  Thanks!  This can be closed, I'll defer to @alphapapa  in case it helps for him to close it for changelog purposes.
