### ISSUE TITLE
"Editing a message" via compose buffer becomes "replying to a message" instead

### ISSUE THREAD

**Issue by phil-s** [alphapapa/ement.el#189]
I'm seeing the following behaviour:

* Type `<insert>` to invoke `ement-room-edit-message`
* Type `C-c '` to invoke `ement-room-compose-from-minibuffer`

The new compose buffer header line reads:

> Press C-x C-s to send message to room (Test) (Replying to message from phil)

And indeed if I send the message it is a new reply to the original message, quoting it and all.

If I do not use `C-c '` then editing works as expected.

(I have some customisations in this area, but AFAICS they do not affect this, so hopefully you can reproduce it.)

**Comment by phil-s** [comment]
I guess this is due to `ement-room-with-highlighted-event-at` causing `ement-room-replying-to-event` to be set when it's used here:

```el
(defun ement-room-edit-message (event room session body)
  "Edit EVENT in ROOM on SESSION to have new BODY.
The message must be one sent by the local user."
  (interactive (ement-room-with-highlighted-event-at (point)
```

**Comment by alphapapa** [comment]
Thanks for reporting.

**Comment by progfolio** [comment]
> (I have some customisations in this area, but AFAICS they do not affect this, so hopefully you can reproduce it.)

FYI, I am able to reproduce sans customizations.

**Comment by alphapapa** [comment]
That should do it.  Please let me know.  Thanks.

**Comment by progfolio** [comment]
Adam Porter ***@***.***> writes:

> That should do it. Please let me know. Thanks.

Just updated and gave it a shot. Works for me. Thanks!

**Comment by phil-s** [comment]
Works for me, thank you!

I'll need to update my custom code at https://github.com/alphapapa/ement.el/issues/140#issuecomment-1639601194 to support the change, but when I use the standard `M-x ement-room-compose-send` to apply the edit then it's doing the right thing.
