### ISSUE TITLE
Prompt for homeserver instead of assuming it

### ISSUE THREAD

**Issue by 0xSteeW** [alphapapa/ement.el#2]
When trying to connect with `ement-connect`, I am only prompted for my id `@steew:steew.cyou` and password, but not the homeserver.
My actual homeserver is located at `matrix.steew.cyou`, not `steew.cyou`, so it is wrongly trying to request an invalid host.
matrix-client.el did prompt for it so I could connect properly.
Best regards.

**Comment by alphapapa** [comment]
Thanks for the report.

Probably, we should only prompt when the homeserver isn't found.  Prompting when `C-u` is used is another option.

BTW, are you aware of using DNS records and/or the `.well-known` convention to allow clients to automatically find the server hostname?  Please see previous discussion of this issue on the matrix-client.el tracker.  It's [not yet implemented here](https://github.com/alphapapa/ement.el/blob/70e7cc91919ba4c8bbb9a1524ea760f4dccd4b08/ement.el#L132), but can easily be added, like it is in matrix-client: https://github.com/alphapapa/matrix-client.el/blob/d2ac55293c96d4c95971ed8e2a3f6f354565c5ed/matrix-api-r0.3.0.el#L396

**Comment by alphapapa** [comment]
@0xSteeW I think that should fix it.  Please let me know how it works for you.
