### ISSUE TITLE
Room list should not be used with visual-line-mode

### ISSUE THREAD

**Issue by akater** [alphapapa/ement.el#20]
My windows are usually 80 chars wide, and `*Ement Rooms*` looks quite bad: apparently, it expects more width.

I don't see any relevant customization options in `ement-room-list` customization group

An example:

```
           Ement.el                  Ement.el, a Matrix client for Em... 45m8s
30
@akater:matrix.org
           Emacs                     The extensible self-documenting ...      
2h42m42s
372
@akater:matrix.org
```

**Comment by alphapapa** [comment]
Looks like you have `visual-line-mode` enabled, but that is not enabled by Ement, so I guess it's something in your config?  Anyway, try `toggle-truncate-lines`.

**Comment by akater** [comment]
Yes, it's `visual-line-mode`.  Maybe ensure (once only) it's disabled when the buffer is created.  If it can't be done reliably, it's not at ement issue but rather `tabulated-list-mode`'s.

**Comment by alphapapa** [comment]
I don't know why it would even be enabled in a tabulated-list buffer.  It doesn't appear to be in a default Emacs config, so I'd rather not add code to disable it unless there's something I'm missing.

**Comment by treed** [comment]
I had similar issues with osm.el, which were simply because I was using global modes for things that only make sense in certain contexts. I replaced a bunch of global modes with this:

```elisp
  (defun treed/local-modes ()
    (visual-line-mode)
    (show-paren-mode)
    (auto-revert-mode)
    (hl-line-mode))
  (add-hook 'prog-mode-hook #'treed/local-modes)
  (add-hook 'text-mode-hook #'treed/local-modes)
```

Most (all?) modes that I care about these actually being enabled for are derived from either prog-mode or text-mode. This gets what I wanted, without erroneously enabling them in contexts where they don't make sense.

**Comment by alphapapa** [comment]
I don't think there's anything to be done here, so closing this.  But please ping me in a comment if this needs to be reopened.
