### ISSUE TITLE
Unreachable cond clauses in ement-complete-session, ement--room-display-name

### ISSUE THREAD

**Issue by progfolio** [alphapapa/ement.el#219]
ement @ 8363bfc

``` emacs-lisp
In ement-complete-session:
ement-lib.el:18:778 Warning: Useless clause following default ‘cond’ clause
In ement--room-display-name:
ement-lib.el:47:1506 Warning: Useless clause following default ‘cond’ clause
```

I believe cl-etypcase forbids the "otherwise" or t clause. 
Switching to cl-typecase should make the default clauses reachable.

**Comment by alphapapa** [comment]
Thanks but I don't see those in https://github.com/alphapapa/ement.el/commit/8363bfcdc29468b6e618e38ef880c4cc051da57d.  Did you mean a different commit?

**Comment by progfolio** [comment]
That's the commit I'm running. The byte compiler warning was just added this week, though:

https://github.com/emacs-mirror/emacs/commit/c137b5195b633c5c931c35385fdb3e75b9ee5f09

Helped me catch a couple in my packages, too.

**Comment by alphapapa** [comment]
Ah, I see, thanks.  I'll look into those after the next release.
