### ISSUE TITLE
Non-obvious "Join it, or load link with browser?" prompt

### ISSUE THREAD

**Issue by phil-s** [alphapapa/ement.el#241]
I selected a chat URL someone had posted, and ement.el prompted me with:

> Room <nil> not joined on current session.  Join it, or load link with browser?

To which my thought was: "Uh, Yes?"

I.e. It's a `completing-read`, but the prompt comes across like a paradoxical `yes-or-yes-p` query.  Guessing what was happening, I typed TAB and got the completions buffer "2 possible completions: Join room, Load link with browser".

I suspect the code was written with an expectation that users are running some completion framework which *automatically* displays the completions, but that's not the default behaviour and I think this isn't the best way to handle such a query.

How about this:?

```el
(let ((read-answer-short t))
  (read-answer
   "Room not joined on current session. (j)oin it, or (l)oad link with browser? "
   '(("join" ?j "Join room in ement.el")
     ("load" ?l "Load link with web browser"))))
```

**Comment by alphapapa** [comment]
Seems like a good idea.  Thanks.

**Comment by phil-s** [comment]
Before I go ahead with a PR... I wonder if there's a better phrasing/letter for the second option.  `(j)oin` seems sensible, but "load" is a pretty generic word -- in context, "[web] browser" is really the key part of `load link with browser`.

OTOH (`M-x browse-url` notwithstanding) web browsers are "browsing" the web collectively, not "browsing" individual URLs, so `(b)rowse` doesn't work to my mind either.  Firefox and Chromium both use the terminology "Open URL" (and even Emacs sometimes uses "open" in its menus, whereas "load" is something quite different in Emacs); so maybe `(o)pen link in web browser` works slightly better.

Or `Open link in web (b)rowser`; or `Open link in (w)eb browser`.  My initial feeling was that it seems preferably to use the first letter of the first word as the active character, but I'm less convinced of that now.

    Room not joined on current session. (j)oin it, or (l)oad link with browser?
    Room not joined on current session. (j)oin it, or (o)pen link with browser?
    Room not joined on current session. (j)oin it, or open link with (b)rowser?
    Room not joined on current session. (j)oin it, or open link with (w)eb browser?
    Room not joined on current session. (j)oin it, or (b)rowse url?

I admit there's a succinct and familiar ring to the last one, despite my earlier comments, but I don't have a single firm favourite, and there might be something else which is better than those.

What do you think?

**Comment by alphapapa** [comment]
"View with browser?"  "Visit with browser?"  I don't know if those are necessarily better than "open", "load", or "browse", but maybe worth considering.

**Comment by phil-s** [comment]
Whatever the phrasing, but it looks like `read-multiple-choice` provides a nicer implementation than `read-answer` (both were added in Emacs 26).

```el
(read-multiple-choice
 "Room not joined on current session."
 '((?j "join" "Join room in ement.el")
   (?w "web browser" "Open URL in web browser")))
```

**Comment by phil-s** [comment]
Sure thing.  For clarity, did you want the more basic version or the one with the fancier help?

**Comment by alphapapa** [comment]
> Sure thing. For clarity, did you want the more basic version or the one with the fancier help?

I'm comfortable with deferring to your judgment on that.  Since I'm the original developer and you're also a user, your perspective may be more important than mine.

**Comment by alphapapa** [comment]
@phil-s If you're still interested, I'll be glad to merge a PR for this without delay.  It doesn't seem like something that needs much testing first.

**Comment by phil-s** [comment]
Let's leave it for 0.15.  I can't do a PR immediately, and it's a minor thing.

**Comment by phil-s** [comment]
I quite like the verbose help, and I also think the default multi-column help formatting seems awkward in the way in which it wraps lines, so here's a wrapper which resolves those things.

```el
(defun ement-read-multiple-choice (prompt choices &optional help)
  "Wrapper for `read-multiple-choice'."
  (let ((help-format (if help
                         (concat (replace-regexp-in-string "%" "%%" help)
                                 "\n\n%s")
                       "%s"))
        (help-choices (mapconcat (lambda (c)
                                   (format "%c: %s\n" (car c) (caddr c)))
                                 choices)))
    (read-multiple-choice prompt choices
                          (format help-format help-choices))))

(cl-case (car (ement-read-multiple-choice
               "Room not joined on current session."
               '((?j "join" "Join room in ement.el")
                 (?w "web browser" "Open URL in web browser"))
               "\
You are not currently joined to that room.  You can either join the room
in ement.el, or visit the link URL in your web browser."))
  (?j 'join-it)
  (?w 'browse-it))
```

**Comment by phil-s** [comment]
I've just realised that the `browse-url` behaviour here has always resulted in a recursive call to this function :)

I'll fix that while I'm at it...

**Comment by alphapapa** [comment]
Thanks for your work and your patience!
