### ISSUE TITLE
Error running timer ‘plz--respond’: (ement-api-error "500: nil") while trying pantalaimon

### ISSUE THREAD

**Issue by artelse** [alphapapa/ement.el#249]
### OS/platform

Linux

### Emacs version and provenance

A recent compiled master 30.

### Emacs command

Just emacs

### Emacs frame type

GUI

### Ement package version and provenance

0.13

### Actions taken

started ement with:
(ement-connect :uri-prefix "http://localhost:8009")

### Observed results

`Error running timer ‘plz--respond’: (ement-api-error "500: nil")`

### Expected results

Connect via the pantalaimon daemon for encryption support.

### Backtrace

```elisp
Debugger entered--Lisp error: (ement-api-error "500: nil")
  signal(ement-api-error ("500: nil"))
  ement-api-error(#s(plz-error :curl-error nil :response #s(plz-response :version 1.1 :status 500 :headers ((content-type . "text/plain; charset=utf-8") (content-length . "91") (date . "Wed, 03 Jan 2024 22:34:59 GMT") (server . "Python/3.11 aiohttp/3.9.1")) :body "Cannot connect to host localhost:8448 ssl:default [Connect call failed ('127.0.0.1', 8448)]") :message nil))
  plz--respond(#<process plz-request-curl> #<buffer  *plz-request-curl*> "finished\n")
  apply(plz--respond (#<process plz-request-curl> #<buffer  *plz-request-curl*> "finished\n"))
  timer-event-handler([t 26005 57619 620832 nil plz--respond (#<process plz-request-curl> #<buffer  *plz-request-curl*> "finished\n") nil 210000 nil])
```

### Etc.

When started pantalaimon reports:
```
pantalaimon                               
======== Starting daemon for homeserver local-matrix on http://127.0.0.1:8009 ========
(Press CTRL+C to quit)
```
with standard configuration:
```
[local-matrix]
Homeserver = https://localhost:8448
ListenAddress = localhost
ListenPort = 8009
```

**Comment by alphapapa** [comment]
Please see the error message from Pantalaimon in the HTTP response body:
```
"Cannot connect to host localhost:8448 ssl:default [Connect call failed ('127.0.0.1', 8448)]"
```
Then look at your configuration file: You have configured Pantalaimon to try to connect to another port on localhost.

**Comment by artelse** [comment]
Ok, went too quick through the setup and missed `Homeserver` to point to `hhtps://matrix.org`.
When starting a connection through Pantalaimon, does this always need to be through Eval: `(ement-connect :uri-prefix "http://localhost:8009/")` or can this be added to ement config?
Thanks!

**Comment by alphapapa** [comment]
Enable session saving, and then you can reconnect with the `ement-connect` command.
