### ISSUE TITLE
Gentoo: Symbol’s function definition is void: libxml-parse-html-region

### ISSUE THREAD

**Issue by donjuanplatinum** [alphapapa/ement.el#264]
### OS/platform

gentoo linux

### Emacs version and provenance

# emacs-version
```
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.39, cairo version 1.18.0) of 2024-02-04
```
# install-ement
## mirror
elpa-gnu
## config file
```
(use-package ement
  :ensure t
  )
```
# ement-version
0.14

### Emacs command

emacsclient -c

### Emacs frame type

gui

### Ement package version and provenance

0.14

### Actions taken

when open the room list and type RET on a room, the Message buffer type "ement-room--render-html: Symbol’s function definition is void: libxml-parse-html-region"

### Observed results

cant show the message 

### Expected results

show the message

**Comment by alphapapa** [comment]
I guess your Gentoo build of Emacs doesn't include libxml support.  That's the most likely explanation I can think of.  This error has never been reported before and the package is known to install and work correctly in this respect.

**Comment by donjuanplatinum** [comment]
# Solution
edit the /etc/portage/package.use/emacs
```
app-editors/emacs libxml2
```

**Comment by alphapapa** [comment]
Please consider recommending that change to be made upstream.  Ement isn't the only Emacs package that uses libxml2.  Even `eww` requires it, and `eww` is a built-in, prominent feature.
