### ISSUE TITLE
Edition of messages breaks reactions

### ISSUE THREAD

**Issue by dionisos2** [alphapapa/ement.el#277]
### OS/platform

Archlinux (6.8.5)

### Emacs version and provenance

GNU Emacs 29.3

### Emacs command

emacs

### Emacs frame type

GUI

### Ement package version and provenance

0.15

### Actions taken

* Connect to Matrix with Ement
* Open a room
* Write a message
* Add reactions to this message
* Edit this message

### Observed results

All the reactions disappear in Ement (they are still there in the Element-Desktop client), and then if we add new reaction to the message, it shows in Ement, but not in Element-Desktop, and if we add the same reaction in Element-Desktop, it starts to be somewhat broken and sometime we can't remove reaction anymore in Ement.

### Expected results

Reactions should not disappear, and reaction added to edited messages should show in both clients.

### Etc.

Maybe linked to this issue : https://github.com/alphapapa/ement.el/issues/230

**Comment by alphapapa** [comment]
Yeah, makes sense, and #230 is probably the solution.  Thanks for reporting.
