### ISSUE TITLE
Suspected autoload issues on NixOS

### ISSUE THREAD

**Issue by RyanGibb** [alphapapa/ement.el#283]
### OS/platform

NixOS

### Emacs version and provenance

29.4 PGTK from Nixpkgs's emacs29-pgtk, installed with the [NixOS module from home-manager](https://github.com/nix-community/home-manager/blob/master/modules/programs/emacs.nix) with `programs.emacs.enable = true`.

### Emacs command

`emacs`

### Emacs frame type

GUI

### Ement package version and provenance

0.15 from Nixpkgs

### Actions taken

Run `ement-connect` and login.

### Observed results

The first issue I noticed was `Error running timer 'plz--respond': (void-function persist--defvar-1)`.

Next, when calling `ement-list-rooms` I got the error `Symbol's function definition is void: persist--defvar-1`.

I can see that I've succesfully logged in as `ement-view-room` autocompletion was showing me my rooms.

### Expected results

No errors.

### Backtrace

```elisp
Debugger entered--Lisp error: (void-function persist--defvar-1)
  persist--defvar-1(ement-room-list-visibility-cache nil)
  byte-code("\300\301\302\"\210\303\304\302\305\306\307%\210\310\311\312\313\314DD\315\316\317%\210\310\320\312\313\321DD\322\316\317%\210\310\323\312\313\324DD\325\316\326%\207" [persist--defvar-1 ement-room-list-visibility-cache nil custom-declare-group ement-room-list "Options for room list buffers." :group ement custom-declare-variable ement-room-list-auto-update funcall function #f(compiled-function () #<bytecode 0x19800016fe5d4>) "Automatically update the taxy-based room list buff..." :type boolean ement-room-list-avatars #f(compiled-function () #<bytecode 0x1c89d3e352efd4>) "Show room avatars in the room list." ement-room-list-space-prefix #f(compiled-function () #<bytecode 0x198f773c6e814>) "Prefix applied to space names." string] 6)
  command-execute(ement-list-rooms record)
  execute-extended-command(nil "ement-list-rooms" nil)
  funcall-interactively(execute-extended-command nil "ement-list-rooms" nil)
  command-execute(execute-extended-command)
```

### Etc.

Reading https://github.com/alphapapa/ement.el/issues/124, https://github.com/alphapapa/ement.el/issues/8, and 
https://github.com/alphapapa/ement.el#installation it seemed like it might be related to not using Emacs' package management system. Using `quelpa-use-package` seems to have worked instead. I'm new to emacs; do you know how the Nix package might be modified or configured to work? If not, should the recommendation to use it be removed?

**Comment by RyanGibb** [comment]
Hmm, it worked once with the `quelpa-use-package` method but is not exhibiting the previous behaviour. I'm stumped.

**Comment by alphapapa** [comment]
Hi Ryan,

I don't use Nix, so I'm afraid that I can't help you with it.  The error you reported would seem to indicate that the `persist` package was not installed or loaded, which might indicate a problem in the Nix packaging somewhere.  Indeed, installing outside of the Nix system would seem likely to solve the problem.  I guess you should file a bug report with the Nix maintainers.
