### ISSUE TITLE
Images in encrypted rooms aren't viewable

### ISSUE THREAD

**Issue by RyanGibb** [alphapapa/ement.el#284]
### OS/platform

NixOS

### Emacs version and provenance

29.4 PGTK from Nixpkgs's emacs29-pgtk, installed with the [NixOS module from home-manager](https://github.com/nix-community/home-manager/blob/master/modules/programs/emacs.nix) with programs.emacs.enable = true.

### Emacs command

`emacs`

### Emacs frame type

GUI

### Ement package version and provenance

0.15 from Nixpkgs

### Actions taken

I've set up [Pantalaimon](https://github.com/matrix-org/pantalaimon/) for viewing encrypted rooms as described in https://github.com/matrix-org/pantalaimon/issues/154 and pointed ement to it as described in https://github.com/alphapapa/ement.el?tab=readme-ov-file#encrypted-room-support-through-pantalaimon.

### Observed results

Images in unencrypted rooms are shown, but images in encrypted rooms are shown as `[image]`. They link to a URL such as `http://<pantalaimon address>:<pantalaimon port>/_matrix/media/r0/download/<homeserver>/<hash>`.

### Expected results

I expected the image to be shown as in unencrypted rooms.

### Backtrace

```elisp
There was no error.
```

**Comment by alphapapa** [comment]
As far as I know, this is Pantalaimon's responsibility, to make events in encrypted rooms work normally.  I can't offer specific support for Pantalaimon or E2EE in Ement.el.  You could try raising the issue on the Pantalaimon repo, but it's not officially maintained.

**Comment by RyanGibb** [comment]
> As far as I know, this is Pantalaimon's responsibility, to make events in encrypted rooms work normally. I can't offer specific support for
> Pantalaimon or E2EE in Ement.el. You could try raising the issue on the Pantalaimon repo, but it's not officially maintained.

Right, I've filed a bug report with Pantalaimon nonetheless. Thanks for
the help!

**Comment by alphapapa** [comment]
Thanks.
