### ISSUE TITLE
Save session does not work

### ISSUE THREAD

**Issue by TLINDEN** [alphapapa/ement.el#302]
### OS/platform

Linux

### Emacs version and provenance

emacs 29.4

### Emacs command

emacs

### Emacs frame type

gui

### Ement package version and provenance

0.15.1 installed using package.el

### Actions taken

This is my config:
```lisp
(use-package ement
  :config
  (setq ement-save-sessions t
        ement-sessions-file "~/.emacs.d/cache/ement.el"))
```

### Observed results

Ement doesn't save the session, I need to login each time I start emacs/ement. The cache file is not being created at all. No error message is being shown.

### Expected results

No login after first successful one.

### Etc.

Or is there any action I need to take in order to trigger the save session event?

**Comment by phil-s** [comment]
You're doing it wrong -- `setq` doesn't work with the user option `ement-save-sessions` because it has a custom setter function.  You should either be using `setopt` for user options, or else the customize UI.

**Comment by alphapapa** [comment]
The `use-package` `:custom` keyword can also be used for customization options.  Please see the documentation in the readme.
