### ISSUE TITLE
Sending new message should be "in buffer" rather than a "prompt" in minibuffer.

### ISSUE THREAD

**Issue by apoorv569** [alphapapa/ement.el#31]
First thanks for this new client for matrix, this looks and feels really nice and clean from the old `matrix-client.el`.

I noticed that to send a message you need to get to insert mode (as I'm using evil mode) and then press `RET`, then you get a prompt in minibuffer to type a message, to me at least it feels weird, I would prefer to type the message in buffer, like for example how telega or ERC has, just shows a `>` in buffer and you can go to insert mode start typing and press `RET` and send the message.

**Comment by alphapapa** [comment]
Thanks for the kind words.  I'm glad you like it.

This is a design decision.  My earlier Matrix client, my rewrite of `matrix-client.el`, worked that way.  By using the minibuffer we get several benefits "for free," like input history, being able to send messages without the end of the buffer being visible (like when replying to messages that aren't visible from the bottom of the buffer), etc.  It's also a simpler implementation, because the room buffer is read-only, so we don't have to special-case commands based on where the point is.

So I think it's generally a better solution, and I don't plan to change it.

And as far as using EVIL, well, I don't use that, so I can't help you there.  ;)  But there are Doom users in the chat room, so you could talk to them about key bindings and such.

**Comment by apoorv569** [comment]
> Thanks for the kind words. I'm glad you like it.
> 
> This is a design decision. My earlier Matrix client, my rewrite of `matrix-client.el`, worked that way. By using the minibuffer we get several benefits "for free," like input history, being able to send messages without the end of the buffer being visible (like when replying to messages that aren't visible from the bottom of the buffer), etc. It's also a simpler implementation, because the room buffer is read-only, so we don't have to special-case commands based on where the point is.
> 
> So I think it's generally a better solution, and I don't plan to change it.
> 
> And as far as using EVIL, well, I don't use that, so I can't help you there. ;) But there are Doom users in the chat room, so you could talk to them about key bindings and such.

I understand, its not a deal breaker though, just a minor thing. But thanks for clarifying. Will close this now.

**Comment by vizs** [comment]
I suppose you could use the following as a starting point to open the compose buffer from the room.  You also don't lose history this way since the buffer content is fed to the minibuffer rather being sent directly.

    (defun my-ement-room-send-message ()
      (interactive)
      (let ((im current-input-method)
            (message-filter ement-room-send-message-filter)
            (compose-buffer (ement-room-compose-message ement-room ement-session :body "")))
        (with-current-buffer compose-buffer
          (set-input-method im)
          (setf ement-room-send-message-filter message-filter)
          (pop-to-buffer compose-buffer))))

**Comment by phil-s** [comment]
My main frustration with this design is that I often compose a comment over a longish timeframe, maybe pausing to research or test something in the meantime; or I may have to switch to another room to respond to something else in the middle of writing a comment.  The minibuffer-based approach feels very unusual for an Emacs chat UI (albeit I'm mostly only familiar with ERC), and it seems to makes things harder in the above scenarios.

If I have `enable-recursive-minibuffers` set then I *can* start a message in room A and then switch to room B and submit a message, and then return to A again.  But I can't resume my message to A until I've finished writing my message to B and exited the recursion; and I can't even (easily) see what my message to A is for that duration.

**Comment by alphapapa** [comment]
@phil-s Are you familiar with the commands `ement-room-compose-message` (bound to `M-RET`) and `ement-room-compose-from-minibuffer` (bound to `C-c '` when writing in the minibuffer)?

**Comment by phil-s** [comment]
Aha.  I was not.  Apologies, I should have found that.  (I found this instead and thought it corroborated my assumption; but looking back I can see that `ement-room-compose-message` clearly already existed.)  I'll go to the manual first next time!

I do still kinda wish this had an ERC-like approach, but those commands definitely solve the problems I described.

Thank you.

**Comment by phil-s** [comment]
I believe this will be useful for me:

```el
;; Open Ement Compose buffers below the Room buffer.
(add-to-list 'display-buffer-alist
             (cons "^\\*Ement compose: "
                   (cons 'display-buffer-below-selected
                         '((window-height . 6)
			   (inhibit-same-window . t)
                           (reusable-frames . nil)))))
```

I also notice that these buffers are in `fundamental-mode`.  At minimum, I'd suggest:

```el
(define-derived-mode ement-compose-mode text-mode "Ement Compose"
  "Major mode for composing messages for Matrix rooms.")
```

`ement-room-init-compose-buffer` could then enable that and use the mode keymap.  A key binding to abort the message + delete the window would be useful.  And if there were an option to send the message directly without going via the minibuffer, I'd probably have pretty much everything I wanted at that point.

**Comment by alphapapa** [comment]
Actually, I think I'll use a new issue for that, so this issue can remain with its current title to hopefully direct interested users here.
