### ISSUE TITLE
Trying to connect to conduit matrix server results in "sync timed out"

### ISSUE THREAD

**Issue by alexispurslane** [alphapapa/ement.el#318]
### OS/platform

Fedora 41 (silverblue)

### Emacs version and provenance

GNU Emacs 29.4 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0) of 2024-10-10

acquired from rpm-ostree package manager. native compilation and pgtk are enabled

### Emacs command

I run emacs as a systemd server and connect to it from emacsclient

### Emacs frame type

GUI

### Ement package version and provenance

acquired via package-install, version 0.16

### Actions taken

`ement-connect`, enter fully qualified username, then enter the url of my server

### Observed results

sync perpetually timed out:

```
Ement: Checking server’s login flows...
Ement: Logging in with password...
Ement: Sync request sent.  Waiting for response...
Ement: Sync timed out (@username:url).  Syncing again... [1427 times]
```

### Expected results

ement working properly

### Etc.

The server it's trying to connect to is conduwuit version 0.4.5.

**Comment by phil-s** [comment]
Have you tried setting `ement-initial-sync-timeout` very high, in case it really is only a timeout issue?

**Comment by alexispurslane** [comment]
I can try that for sure!
— alexis (she/her)
Sent from Proton Mail Android
-------- Original Message --------On 12/3/24 3:42 PM, phil-s  wrote:
Have you tried setting ement-initial-sync-timeout very high, in case it really is only a timeout issue?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/alphapapa/ement.el/issues/318#issuecomment-2515511371",
"url": "https://github.com/alphapapa/ement.el/issues/318#issuecomment-2515511371",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alexispurslane** [comment]
> Have you tried setting `ement-initial-sync-timeout` very high, in case it really is only a timeout issue?

setting it to 1000 worked lmao

**Comment by alphapapa** [comment]
> > Have you tried setting `ement-initial-sync-timeout` very high, in case it really is only a timeout issue?
> 
> setting it to 1000 worked lmao

That would seem to suggest that the server is taking an unusually long time to prepare an initial sync response.  Maybe it's a bug in the server implementation, or maybe the system is overloaded.
