### ISSUE TITLE
Remember and verify login.

### ISSUE THREAD

**Issue by apoorv569** [alphapapa/ement.el#32]
Is it possible to remember and verify the login/session details, currently when I open `Emacs` I have to run `ement-connect` and enter my username and password to login, and if I close and reopen `Emacs` it forgets the login details, and I have to login again. Is there some variable that I can set for my username, server and a password command, like for using with `gpg` probably. As I have my configuration on a public repository, so I don't want to expose my password.

**Comment by edgar-vincent** [comment]
I use: 
```
(defun my/ement-connect ()
  (interactive)
  (ement-connect :uri-prefix "http://localhost:8009"
                 :user-id "@user:server.org"
                 :password (+pass-get-secret "Path/to/secret·")))
```

I use `pass` directly, but you could also use `auth-source`.

**Comment by alphapapa** [comment]
Please look in the customization options:

https://github.com/alphapapa/ement.el/blob/fce250fee1a15cdc48ab83fb5f8f9e6fafaf96d9/ement.el#L106
