### ISSUE TITLE
Should ement-room-image-keymap be a child of image-map?

### ISSUE THREAD

**Issue by vizs** [alphapapa/ement.el#39]
image-map has keys defined for scaling and rotating images.  I think
it would be handy to have these commands so we can resize/rotate images
in-buffer.  Org-mode, for instance, puts this keymap in the inline
image overlay.

ement-room-image-scale-mouse breaks after scaling the image with +/- though since
(image-property image :max-height) evaluates to nil.

**Comment by alphapapa** [comment]
Maybe so.  If you'd like to test that out and report on the results, feel free.  :)

**Comment by vizs** [comment]
Closing in favour of #67.

**Comment by phil-s** [comment]
I suggest a call to `numberp` in place of the somewhat mysterious "impossible dummy value -1" which had me scratching my head wondering where that was set before I realised it was *purely* there to avoid an error from the `=` numeric equality check.

```diff
   (pcase-let* ((image (get-text-property pos 'display))
+               (max-height (image-property image :max-height))
                (window-width (window-body-width nil t))
                (window-height (window-body-height nil t))
-               ;; Image scaling commands set :max-height and friends to nil so use the
-               ;; impossible dummy value -1.  See <https://github.com/alphapapa/ement.el/issues/39>.
-               (new-height (if (= window-height (or (image-property image :max-height) -1))
+               ;; Image scaling commands set :max-height and friends to nil.
+               ;; See <https://github.com/alphapapa/ement.el/issues/39>.
+               (new-height (if (and (numberp max-height) (= window-height max-height))
```

**Comment by phil-s** [comment]
Or just use `eql`, if it's *not* possible that it might be comparing an int with a float?  (I wasn't sure.)

**Comment by alphapapa** [comment]
Ok, I'll merge a PR if you'll send it.

**Comment by phil-s** [comment]
Addressed in https://github.com/alphapapa/ement.el/pull/255
