### ISSUE TITLE
feature request: file upload/download support

### ISSUE THREAD

**Issue by martinmake** [alphapapa/ement.el#43]
I use matrix as a simple way to share files between people/devices.

From what I've seen, I can tell that there isn't a way to upload/download files (or maybe it's just not well documented?).  It doesn't seem like that difficult of a feature to add. The terminal client *gomuks* supports it.

However, I don't have much experience with elisp to easily add it, so any tips would be appreciated if you're not interested in adding this feature.

It would also be cool to have a list view of room's media/files - just like in *Element*.  I can create a separate feature request for this if you wish.

**Comment by alphapapa** [comment]
Hi Martin,

Yes, uploading files is essentially the same action as uploading images.  I just haven't needed to do this yet, so I haven't bothered adding the command yet.  It should only require a few changes to the image-uploading code to upload files.  

If you'd like to try it yourself, see the relevant image-uploading code in `ement-room.el`.  Please note that I intend to add Ement.el to GNU ELPA in the future, so if you intend to contribute code, you'd need to have FSF copyright assignment.  If not, I'll get around to adding the command eventually.

Listing rooms' media is a good idea.  Yes, please file that separately.

**Comment by alphapapa** [comment]
Oops, this was added in https://github.com/alphapapa/ement.el/commit/be5d68cd2c4eb662528b4ee17d16059d099c82e3
