### ISSUE TITLE
Image insertion: "wrong-type-argument consp nil"

### ISSUE THREAD

**Issue by jave** [alphapapa/ement.el#45]
I encounter "wrong-type-argument consp nil" when trying to use ement.el.

I include the trace below.

I use a recently built emacs from master.

I guess something goes wrong with setting image properties?

/Joakim

Debugger entered--Lisp error: (wrong-type-argument consp nil)
  image--set-property(nil :max-height 24)
  ement--resize-image(nil nil 24)
  ement-room-list--entry(#s(ement-session :user ... :server ... :token "syt_am9ha2lt_t..." :transaction-id 2465066195 :rooms ... :next-batch "s87075_102557_..." :device-id "RARSEKDBBL" :initial-device-display-name nil :has-synced-p t :account-data ... :events #<hash-table equal 371/487 0x1acb65d>) #s(ement-room :id "!QvxjshMimBMyV..." :display-name "gitlab/gitlab" :prev-batch "t3408--98_1025..." :summary ... :state ... :timeline ... :ephemeral nil :account-data ... :unread-notifications nil :latest-ts 1636729310691 :topic "Version Contro..." :canonical-alias "#gitlab_gitlab..." :avatar ... :type join ...))
  #f(compiled-function (room) #<bytecode 0x1b0092d6f92d1489>)(#s(ement-room :id "!QvxjshMimBMyVIijfP:..." :display-name "gitlab/gitlab" :prev-batch "t3408--98_102549_102..." :summary (... ...) :state (... ... ... ... ... ... ... ... ... ... ...) :timeline (... ... ... ... ... ... ... ... ... ...) :ephemeral nil :account-data (...) :unread-notifications nil :latest-ts 1636729310691 :topic "Version Control on y..." :canonical-alias "#gitlab_gitlab:gitte..." :avatar #(" " 0 1 ...) :type join :invite-state nil :local (... ...)))
  ement-room-list--set-entries()
  tabulated-list-revert(nil nil)
  revert-buffer()
  ement-room-list-auto-update(#s(ement-session :user ... :server ... :token "syt_am9ha2lt_t..." :transaction-id 2465066195 :rooms ... :next-batch "s87075_102557_..." :device-id "RARSEKDBBL" :initial-device-display-name nil :has-synced-p t :account-data ... :events #<hash-table equal 371/487 0x1acb65d>))
  run-hook-with-args(ement-room-list-auto-update #s(ement-session :user ... :server ... :token "syt_am9ha2lt_t..." :transaction-id 2465066195 :rooms ... :next-batch "s87075_102557_..." :device-id "RARSEKDBBL" :initial-device-display-name nil :has-synced-p t :account-data ... :events #<hash-table equal 371/487 0x1acb65d>))
  ement--sync-callback(#s(ement-session :user ... :server ... :token "syt_am9ha2lt_t..." :transaction-id 2465066195 :rooms ... :next-batch "s87075_102557_..." :device-id "RARSEKDBBL" :initial-device-display-name nil :has-synced-p t :account-data ... :events #<hash-table equal 371/487 0x1acb65d>) (... ... ... ...))
  apply(ement--sync-callback (... ...))
  #f(compiled-function (&rest args2) #<bytecode -0xae4d5759041c51d>)(((next_batch . "s87075_102557_1032_3749_508_4_166_24818_1") (device_one_time_keys_count (signed_curve25519 . 0)) (org\.matrix\.msc2732\.device_unused_fallback_key_types . []) (rooms (join (!JHAvEUUQKeqCqhJduQ:verona\.se (timeline (events . []) (prev_batch . "s87075_102555_1031_3749_508_4_166_24818_1") (limited . :json-false)) (state (events . [])) (account_data (events . [])) (ephemeral (events . [...])) (unread_notifications (notification_count . 0) (highlight_count . 0)) (summary) (org\.matrix\.msc2654\.unread_count . 0))))))
  #f(compiled-function () #<bytecode 0xedcb3490649e78c>)()
  plz--sentinel(#<process plz-request-curl> "finished\n")
  ement-room-read-string("Send message (Pelle (Signal)): " nil nil nil inherit-input-method)
  byte-code("\10\204\10\0\305\300!\210\11\204\20\0\305\301!\210\10\11\306\307\310\4!\n>\204$\0\311\312\300\6\6D\"\210\3\313H\"\314\216\13\203>\0\f\2036\0..." [ement-room ement-session cl-struct-ement-room-tags ement-room-send-typing ement-room-typing-timer cl--assertion-failed format "Send message (%s): " type-of signal wrong-type-argument 2 #f(compiled-function () #<bytecode 0x6e043aa79b3f2c>) cancel-timer run-at-time nil 15 ement-room--send-typing ement-room-read-string inherit-input-method :body] 9)
  command-execute(ement-room-send-message)

**Comment by alphapapa** [comment]
This probably indicates that an image failed to download or be loaded properly, and the nil value is unexpected.  Does this happen every time you connect, or only when you do certain actions?

**Comment by jave** [comment]
every time I connect with ement, to my own matrix server, I havent tried another one.

Another user can connect to my server with ement, and it works for him.

**Comment by user-09876** [comment]
It also happens to me using `emacs -nw`. The emacs GUI seems to throw no error otherwise.

**Comment by alphapapa** [comment]
FYI, I recently pushed this change, which may also fix this problem: https://github.com/alphapapa/ement.el/commit/44580a8a252836c1675bb51b0674a543b75f5beb  Please let me know if it still happens.

**Comment by alphapapa** [comment]
Haven't seen or heard about this since then, so closing.  Please ping me or open a new issue if it happens again.
