### ISSUE TITLE
feature request: load `ement-room-scroll-down` when top of buffer reached

### ISSUE THREAD

**Issue by edgar-vincent** [alphapapa/ement.el#46]
Hello,

Would it be possible for `ement-room-scroll-down` to be called when the point is at the top of the buffer and `previous-line` (or `scroll-up`) is called? It would make it easier to go back in history when reading missed messages and prevent having to remember to call `ement-room-scroll-down` specifically.

As always, thanks a lot for your work.

EV

**Comment by alphapapa** [comment]
Hi,

This should already happen.  If there are some commands that aren't properly bound in room buffers, please enumerate them and we can wrap or rebind them properly.  (Patches also welcome, of course.  See https://github.com/alphapapa/ement.el/blob/c951737dc855604aba389166bb0e7366afadc533/ement-room.el#L95

**Comment by edgar-vincent** [comment]
Oh, indeed, sorry about that. It's probably a conflict with evil-mode or Doom. I'll try and write a patch!

**Comment by alphapapa** [comment]
Okay, since it's probably due to EVIL or Doom, I'll close this.  Maybe you could add a workaround to `evil-collection`.
