### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by divansantana** [alphapapa/ement.el#50]
Hello,

I'm trying to install this package on my openbsd system.

I've tried with quelpa and the plz package installs but ement errors with:

```
Debugger entered--Lisp error: (file-missing "Opening input file" "No such file or directory" "/home/ds/.cache/emacs/quelpa/packages/ement-202110...")
  insert-file-contents("/home/ds/.cache/emacs/quelpa/packages/ement-202110..." nil nil nil nil)
  insert-file-contents-literally("/home/ds/.cache/emacs/quelpa/packages/ement-202110...")
  quelpa-get-package-desc("/home/ds/.cache/emacs/quelpa/packages/ement-202110...")
  quelpa-package-install((ement :fetcher github :repo "alphapapa/ement.el"))
  apply(quelpa-package-install (ement :fetcher github :repo "alphapapa/ement.el") nil)
  quelpa((ement :fetcher github :repo "alphapapa/ement.el"))
  eval((quelpa '(ement :fetcher github :repo "alphapapa/ement.el")) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

I tried installing ement like so:

```
  ;; Install `plz' HTTP library (not on MELPA yet).
  (quelpa '(plz :fetcher github :repo "alphapapa/plz.el"))

  ;; Install Ement.
  (quelpa '(ement :fetcher github :repo "alphapapa/ement.el"))
```

I then tried to git clone the repo and install with:

```
./makem.sh compile
```

which fails with:

```
getopt: unknown option -- o
getopt: unknown option -- l
```

It then prints the usage.

Would you know what's going wrong?

**Comment by alphapapa** [comment]
Hello,

I would guess that installing with Quelpa would work on OpenBSD, but since it does shell out to git, maybe there are some incompatibilities.  As well, you didn't mention which Emacs version you're using, so that might be relevant.

`makem.sh` is written to work with GNU `getopt`, which is incompatible with BSD-style `getopt`.  You can find some more information on the `makem.sh` repo and issues linked from there.

**Comment by divansantana** [comment]
thanks for the help.  Sorted now, used gnu getopt.

**Comment by alphapapa** [comment]
@divansantana Good, thanks.  FYI, `./makem.sh compile` isn't intended to be used as a way to install packages, but if it works that way, cool.  :)
