### ISSUE TITLE
Prevent membership events from marking rooms unread

### ISSUE THREAD

**Issue by bbigras** [alphapapa/ement.el#56]
I don't know if there's already something for that, but often, when I'm looking at the room list I think that a room has new messages, but it's only some join/leave or nick changes.

Does the room list make the distinction between all events vs unread messages?

**Comment by alphapapa** [comment]
The unread status of a room is determined by the room's buffer's modified status in Emacs.  What we need is an option to use `with-silent-modifications` when inserting membership events into a buffer.  Thanks for the suggestion, I'd like to use it myself.

**Comment by alphapapa** [comment]
Hm, well, as you can see here, that is already the case:

https://github.com/alphapapa/ement.el/blob/ce8ee9b5b49b9fdb51f3b94d9b8e503326611ce2/ement-room.el#L1946

So join/leave events should already not cause a room's unread status to be changed.  If you can, please be more specific about exactly which events seem to be causing a room to be marked as unread.  Thanks.

**Comment by bbigras** [comment]
I might be mixing things.

Is it documented what the 3 columns are for?

![image](https://user-images.githubusercontent.com/24027/159095960-0f27640d-28b0-4f5c-b955-0037862aef61.png)

Also, the "latest" column. Is it for all the events?

**Comment by alphapapa** [comment]
Each column header has a tooltip that explains what it is.

> Also, the "latest" column. Is it for all the events?

Yes, each room has a latest-timestamp slot that is updated when processing new events, see https://github.com/alphapapa/ement.el/blob/ce8ee9b5b49b9fdb51f3b94d9b8e503326611ce2/ement.el#L638

**Comment by bbigras** [comment]
Ok, I think I was mixing things up.

So my room list is sorted by "latest" and I assumed that the rooms at the top had new messages.

And I didn't realize that I had to join a room first, to open a buffer, to get the (U)nread flag in the room list.

Is there a way to auto-create some buffers for my favorite rooms on connect?

**Comment by alphapapa** [comment]
> Ok, I think I was mixing things up.
> 
> So my room list is sorted by "latest" and I assumed that the rooms at the top had new messages.
> 
> And I didn't realize that I had to join a room first, to open a buffer, to get the (U)nread flag in the room list.

Ok, good, I think there is no bug here.
 
> Is there a way to auto-create some buffers for my favorite rooms on connect?

Yes, see the customization options.
