### ISSUE TITLE
Pantalaimon: "Encrypted by an unverified session"

### ISSUE THREAD

**Issue by fleimgruber** [alphapapa/ement.el#60]
Using Pantalaimon with this config:

```
[Default]
LogLevel = Debug
SSL = True

[local-matrix]
Homeserver = https://matrix.org
ListenAddress = localhost
ListenPort = 8009
SSL = False
UseKeyring = False
IgnoreVerification = True
```

When I send messages in an encrypted direct private room, they are shown with a red shield in Element.io with the message "Encrypted by an unverified session". How to verify the ement.el session?

**Comment by alphapapa** [comment]
AFAIK this is an issue to do with Pantalaimon, not with Ement.el, and I don't use Pantalaimon, so I can't help you with it.  Please ask for help in the chat room.
