### ISSUE TITLE
Loading old messages failed on first connect

### ISSUE THREAD

**Issue by yantar92** [alphapapa/ement.el#62]
When I just installed ement, ran M-x ement-connect, joined Ement.el room, and tried to load older messages with S-<SPACE>, the messages where not loaded. Instead, I got an error:

    ​error in process sentinel: Ement API error: "Loading earlier
    messages failed", #s(plz-error nil #s(plz-response 2 400 ((date .
    "Wed, 13 Apr 2022 15:44:44 GMT") (content-type .
    "application/json") (synapse-trace-id . "...") (cache-control .
    "no-cache, no-store, must-revalidate")
    (access-control-allow-origin . "*") (access-control-allow-methods
    . "GET, HEAD, POST, PUT, DELETE, OPTIONS")
    (access-control-allow-headers . "X-Requested-With, Content-Type,
    Authorization, Date") (permissions-policy . "interest-cohort=()")
    (cf-cache-status . "DYNAMIC") (expect-ct . "max-age=604800,
    report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"")
    (server . "cloudflare") (cf-ray . "...-IAD"))
    "{\"errcode\":\"M_UNKNOWN\",\"error\":\"'from' parameter is
    invalid\"}") nil)

Running M-x ement-disconnect + M-x ement-connect solved the problem for now.

Also, M-x ement-disconnect threw another error:

    error in process sentinel: Ement API error: "Ement: Unrecognized network error", #s(plz-error nil nil "curl process killed")

**Comment by alphapapa** [comment]
Thanks.  Somehow the "from" token must not be getting received or saved when a room is joined, but it comes in with a full sync.

**Comment by alphapapa** [comment]
@yantar92 I hate to ask, "Does this still happen?" but I'm afraid I have to, because AFAIK I've never had this problem myself.

**Comment by alphapapa** [comment]
Thanks.
