### ISSUE TITLE
Editing formatted message

### ISSUE THREAD

**Issue by yantar92** [alphapapa/ement.el#65]
I just tried to send a message composed in org buffer (I have `(setq ement-room-send-message-filter #'ement-room-send-org-filter)`). Then, I edited it quickly in the modeline and confirmed the edit.

Expected behaviour: Org formatting is preserved

Observed behaviour: Plain text is displayed after the edit.

**Comment by yantar92** [comment]
The formatting is preserved when I view the message in another client.

The edited message in ement is displayed as:

"  yantar92​[unknown body format: nil] ~/etc/mailcap~ and ~~/.mailcap~ are checked by Emacs first. They usually link pdf to ~xdg-open~. Can you show the contents of your mailcap files? [edited]"

**Comment by alphapapa** [comment]
Thanks, I've been aware of this bug but it doesn't happen often so I haven't looked into it yet.

I'm not sure of the best way to handle it.  We might need to send the Org formatted text in the original event so we can reuse it when editing.  I guess that's allowed by the spec, although it would mean sending the message body in 3 different formats.

**Comment by alphapapa** [comment]
I just tested this and it seems to work now, so closing.  Please let me know if anyone finds otherwise.
