### ISSUE TITLE
Provide default numeric values in list-latest<

### ISSUE THREAD

**Issue by akater** [alphapapa/ement.el#7]
This is how the tail of my `*Ement Rooms*` buffer looks now:

```
some-chat                               3y257d13h53m38s  @akater:matrix.org
F-Droid    F-Droid, the free...                          @akater:matrix.org
Ement.el   Ement.el, a Matrix client...                  @akater:matrix.org
```

Observe that the last several chats don't have a latest-time label.

Here's current definition of `list-latest<`:

```lisp
(defun ement-room-list-latest< (a b)
  "Return non-nil if entry A has fewer members than room B.
A and B should be entries from `tabulated-list-mode'."
  (pcase-let* ((`(,_room [,_name-for-list ,_topic ,a-latest ,_session]) a)
               (`(,_room [,_name-for-list ,_topic ,b-latest ,_session]) b))
    (< (get-text-property 0 'value a-latest)
       (get-text-property 0 'value b-latest))))
```

Entities corresponding to the last two chats above had empty strings for their a-latest / b-latest.  Consequently, `get-text-property` returned nil and `<` errored.  So I had to alter `list-latest<` to be able to use Ement:

```lisp
(defun ement-room-list-latest< (a b)
  "Return non-nil if entry A has fewer members than room B.
A and B should be entries from `tabulated-list-mode'."
  (pcase-let* ((`(,_room [,_name-for-list ,_topic ,a-latest ,_session]) a)
               (`(,_room [,_name-for-list ,_topic ,b-latest ,_session]) b))
    (< (or (get-text-property 0 'value a-latest) 0)
       (or (get-text-property 0 'value b-latest) 0))))
```

I don't know how to reproduce the bug; the rooms in question are different each time.  However, i think that providing a default numeric value is reasonable anyway.  But maybe you have better ideas for this so this is not a PR.

**Comment by alphapapa** [comment]
AFAIK if any room doesn't have a latest timestamp, that's a bug that needs to be fixed.  I haven't seen that happen in any of my rooms.

**Comment by akater** [comment]
I agree but it's still better when Ement is working than when it's not.  Thus, this '<' call better get numeric arguments in all cases.

**Comment by akater** [comment]
Bug won't be obscured when the field is clearly empty.  It might be obscured when a-latest / b-latest is a property-less string.

**Comment by alphapapa** [comment]
I'd rather just fix the underlying bug.  Next time you encounter this, we can check the room struct's latest timestamp slot and see what's going on.

**Comment by akater** [comment]
Resolved, thank you!
