### ISSUE TITLE
Feature Request: Save Complete Room Log

### ISSUE THREAD

**Issue by jgarte** [alphapapa/ement.el#72]
Could `ement.el` support saving a complete room log?

I'd like to be able to just run a command in a transient buffer to save the room log.

wdyt

I'd prefer to save the logs using just emacs instead of having to use an external program like the following unmaintained script:

https://matrix.org/docs/projects/other/matrix-recorder

**Comment by alphapapa** [comment]
What do you mean by "complete"?

Also, have you tried `C-x C-w`?

**Comment by jgarte** [comment]
> What do you mean by "complete"?

By "complete", I mean since the room was created or if that's not possible since the time I joined the room.
 
> Also, have you tried `C-x C-w`?

I have not yet. I'll try it soon. Thanks for the help.

**Comment by alphapapa** [comment]
To elaborate slightly, Matrix, as-is, seems to suffer from a "gappy sync" problem, which is mostly only relevant for this particular use case, i.e. saving a complete history of a room's events.  You can find various discussions of this on the Matrix spec-related repos in various MSC proposals.  When the fetching-events-by-timestamp MSC is merged, this would become much more practical.  

In the meantime, this is really out-of-scope for Ement.el (and maybe always will be).  If you want to have the complete history of a room, you probably need to use that `matrix-recorder` script, or actually run your own homeserver federated into the network (and then I guess you'd have to manually make it fetch all events in a room's history from the rest of the network).
