### ISSUE TITLE
Notification error: (dbus-error "org.freedesktop.DBus.Error.ServiceUnknown" "The name org.freedesktop.Notifications was not provided by any .service files") 

### ISSUE THREAD

**Issue by tsdh** [alphapapa/ement.el#83]
I run ement on a server where I ssh into.  On that server, there's no notification daemon installed so whenever ement wants to send a notification via dbus, I get the error from the subject.

I guess it would be better if ement checks for availability of the dbus notification service before sending and producing a distracting error message.  A function for doing so would be:

```elisp
(defun th/dbus-notifications-available-p ()
  (and (featurep 'dbusbind)
       (require 'dbus nil :no-error)
       (dbus-ignore-errors (dbus-get-unique-name :session))
       (dbus-ping :session "org.freedesktop.Notifications")))
```

**Comment by alphapapa** [comment]
@tsdh Thanks!
